### ISSUE TITLE
Social Media Accounts: Common Name

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/infrastructure-tracking#1]
We should build out some social media accounts.
This story is for agreement on a common-name to use among them.

There should multiple accounts:
- Vega Strike Engine
- Any games we manage (f.e Upon the Coldest Sea)

Proposal for current stuff:

Core Engine:
- [ ] VegaStrikeGaming (core engine)

Game Play: Upon the Coldest Sea
- [ ] UponTheColdestSea
- [ ] VegaStrikeUponTheColdestSea
- [ ] VSUponTheColdestSea

Note: The above is the `non-space` version; if a platform allows it then we can add spaces. I don't think Twitter allows spaces.

**Comment by BenjamenMeyer** [comment]
NOTE: As much as I'd like to use VegaStrike it's already taken on Twitter. The account is inactive but without filing a complaint with Twitter (which I'd rather not do) there's not likely any way to get access to it. The content on it also doesn't match up to our VS UtCS game, so the user isn't likely related to us at all. Thus my proposals above for some different names.

NOTE: https://help.twitter.com/en/rules-and-policies/inactive-twitter-accounts - unless we hold a trademark (which we can't afford) they won't release an inactive account.

**Comment by BenjamenMeyer** [comment]
Part of what I posted in Gitter:

> We do already have a FB page, though I'm not sure who has access right now - we'll have to track them down so we can open up access; and there's an existing Twitter account by our basic name (vegastrike) held by someone in Brazil. While I'd like to have the Twitter account for common naming - it'd make things easy - they've done nothing to claim they're us or anything, and honestly VegaStrike wasn't active when they created the account either - they're also out of Brazil IIRC. So I see no reason to report them - let's only do that for truly nefarious accounts where there is real reason to do so (right now it's mostly a lack of ability to contact that person); thus we need to create a new name that we can unify across our platforms for social media marketing purposes.


Basically - let's be civil and nice as much as possible. Unfortunately the options Twitter provides doesn't cover our situation.

**Comment by stephengtuggy** [comment]
How about Vega_Strike? Could we use that everywhere?

**Comment by stephengtuggy** [comment]
And I believe Twitter handles are limited to 20 characters, so if we want to use the same handle everywhere for UtCS, it should probably be UnderTheColdestSea or VSUnderTheColdestSea.

**Comment by stephengtuggy** [comment]
Wait a second. Isn't it supposed to be UponTheColdestSea? (Or VSUponTheColdestSea)

**Comment by BenjamenMeyer** [comment]
@stephengtuggy yes; old misunderstanding

**Comment by BenjamenMeyer** [comment]
Once I finish up the infrastructure for Digital Ocean, then I'm going to get back on setting up the social media stuff.

**Comment by BenjamenMeyer** [comment]
I put up my current infrastructure stuff so others can pull and review; going to divert over here to get this stuff started at least.

**Comment by BenjamenMeyer** [comment]
List of social media platforms to setup and their respective issues:

VegaStrikeGaming
- [x] Twitter (#2)
- [ ] Facebook (#3, #5)- https://www.facebook.com/VegaStrike-188522714499479/
- [x] PlusPora/Diaspora (#13)
- [x] MeWe (#12)
- [x] YouTube (#14) - https://www.youtube.com/channel/UC5p9ObADzS3sx9orZG7M91g/

VS: Upon The Coldest Sea
- [x] Twitter (#2)
- [x] Facebook (#3) - ~subpage of https://www.facebook.com/VegaStrike-188522714499479/? Or new page?~ https://www.facebook.com/VSUponTheColdestSea/
- [x] PlusPora/Diaspora (#13)
- [x] MeWe (#12)
- [ ] YouTube (#14)

**Comment by BenjamenMeyer** [comment]
I need some videos to post to create the YouTube channels so tabling that for the 0.7.x release.

**Comment by BenjamenMeyer** [comment]
We've got enough social presence now to make the release.

**Comment by BenjamenMeyer** [comment]
Remaining things can be done for the 0.7.x release, may be 0.8.x or even 0.9.x if need be.

**Comment by BenjamenMeyer** [comment]
Status Summary:
- We need 100 Subscribers on our YouTube Page, some branding artwork, etc. so that we can get a custom URL in youtube
- We can post to the Vega Strike FB page, but we don't have any admin access to it

NOTE: The VS:UtCS page got classified as a business page b/c I was poking around with tooling on FB. Not a big deal... I just get harassed by FB about spending money on advertising and offers for free credit if I spend so much on advertising (e.g Spend $300 get another $150 in credit, effectively making a $450 advertising campaign). I have no intention of spending money on advertising.

**Comment by BenjamenMeyer** [comment]
I don't see anything more changing for 0.7.x or 0.8.x

**Comment by BenjamenMeyer** [comment]
https://github.com/vegastrike/infrastructure-tracking/wiki/Announcements:-How-to

**Comment by stephengtuggy** [comment]
Looks good. Can this issue be closed?

**Comment by BenjamenMeyer** [comment]
yes, since it's all documented in that Wiki page we can close this.
